# Generated by Django 5.2.1 on 2025-07-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.IntegerField(blank=True, choices=[(1, 'کمتر از کارشناسی'), (2, 'کارشناسی'), (3, 'کارشناسی ارشد'), (4, 'دکتری'), (5, 'دیگر')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='english_first_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='english_last_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'مرد'), (2, 'زن'), (3, 'دیگر')], db_index=True, null=True),
        ),
    ]
