# Generated by Django 5.2.1 on 2025-06-04 17:49

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='_updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
