# Generated by Django 5.2.1 on 2025-07-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_referer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmlog',
            name='action',
            field=models.IntegerField(choices=[(1, 'تماس موفق'), (2, 'تماس ناموفق'), (3, 'پیامک ارسال شد'), (4, 'تلگرام ارسال شد')], db_index=True, default=1),
        ),
    ]
