# Generated by Django 5.2.1 on 2025-07-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_crmlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.IntegerField(blank=True, choices=[(1, 'کمتر از کارشناسی'), (2, 'کارشناسی'), (3, 'کارشناسی ارشد'), (4, 'دکتری و بالاتر'), (5, 'دیگر')], null=True),
        ),
    ]
