# Generated by Django 5.2.4 on 2025-07-04 08:34

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmuser',
            name='last_follow_up',
            field=django_jalali.db.models.jDateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='next_follow_up',
            field=django_jalali.db.models.jDateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
