# Generated by Django 5.2.4 on 2025-07-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_crmuser_last_follow_up_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crmuser',
            old_name='support_user',
            new_name='supporting_user',
        ),
    ]
