# Generated by Django 5.2.4 on 2025-07-12 13:47

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_city_alter_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmUserLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('_updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['-_created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='crmuser',
            name='crm_label',
            field=models.ManyToManyField(blank=True, related_name='crm_users', to='users.crmuserlabel'),
        ),
    ]
