# Generated by Django 5.2.4 on 2025-07-04 21:15

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_support_user_crmuser_supporting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmlog',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
