# Generated by Django 5.2.4 on 2025-07-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0007_crmuserlabel_crmuser_crm_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmlog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='crmuserlabel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='orgnization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-_created_at']},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['national_id'], name='users_user_nationa_7d24c6_idx'),
        ),
    ]
