# Generated by Django 5.2.4 on 2025-07-18 13:26

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_crmlog_options_alter_crmuserlabel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmlog',
            name='date',
            field=django_jalali.db.models.jDateTimeField(blank=True, db_index=True, default=jdatetime.datetime.now),
        ),
    ]
