# Generated by Django 5.2.4 on 2025-07-18 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_crmlog_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orgnization',
            new_name='Organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='orgnization',
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_users', to='users.organization'),
        ),
    ]
