# Generated by Django 5.2.4 on 2025-07-20 19:06

import django.db.models.deletion
import django_jalali.db.models
import jdatetime
import phonenumber_field.modelfields
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_orgnization_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('_updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('line_number', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('_updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None)),
                ('text', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Sent'), (2, 'Failed')], db_index=True, default=0)),
                ('response', models.JSONField(blank=True, null=True)),
                ('date', django_jalali.db.models.jDateTimeField(blank=True, db_index=True, default=jdatetime.datetime.now)),
                ('line_number', models.ForeignKey(blank=True, default=users.models.SMSLine.get_available_line, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='users.smsline')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-_created_at'],
            },
        ),
    ]
