# Generated by Django 5.2.4 on 2025-07-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_smsline_smslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsline',
            name='provider',
            field=models.IntegerField(blank=True, choices=[(0, 'Elanak'), (1, 'Kavenegar')], default=1),
        ),
    ]
