# Generated by Django 5.2.4 on 2025-07-20 22:06

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_smsline_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmlog',
            name='date',
            field=django_jalali.db.models.jDateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='date',
            field=django_jalali.db.models.jDateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
    ]
