# Generated by Django 5.2.4 on 2025-07-30 06:27

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_crmlog_date_alter_smslog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmlog',
            name='date',
            field=django_jalali.db.models.jDateTimeField(blank=True, db_index=True),
        ),
    ]
