[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "staticfiles",
    "migrations",
]

# Same as Black.
line-length = 120
indent-width = 4

# Assume Python 3.11
target-version = "py311"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = [
    "E4",    # pycodestyle errors
    "E7",
    "E9",
    "F",     # Pyflakes
    "I",     # isort
    "N",     # pep8-naming
    "UP",    # pyupgrade
    "S",     # flake8-bandit
    "B",     # flake8-bugbear
    "C4",    # flake8-comprehensions
    "DJ",    # flake8-django
    "PIE",   # flake8-pie
    "T20",   # flake8-print
    "RUF",   # Ruff-specific rules
]

ignore = [
    "S101",  # Use of assert detected (OK in tests and Django code)
    "DJ001", # Avoid using null=True on string-based fields
    "N806",  # Variable in function should be lowercase (Django models use CamelCase)
    "N815",  # Variable in class scope should not be mixedCase (Django Meta class)
    "RUF012",
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint.isort]
known-first-party = ["neshaa", "users", "courses", "financials"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.ruff.lint.per-file-ignores]
"**/migrations/*" = ["ALL"]
"**/settings/*" = ["F405", "F403"]  # Allow * imports in settings
"**/populate_db.py" = ["S106", "T201"]
"manage.py" = ["T20"]
"notebooks/*" = ["ALL"]  # Ignore notebooks
"**/tests.py" = ["S101"]  # Allow assert in tests
"**/test_*.py" = ["S101"]  # Allow assert in tests