# Generated by Django 5.2.1 on 2025-06-05 11:04

import commons.models
import django.contrib.admin.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedLog',
            fields=[
                ('logentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin.logentry')),
                ('old_values', models.JSONField(decoder=commons.models.LogDecoder, encoder=commons.models.LogEncoder)),
                ('changed_values', models.JSONField(decoder=commons.models.LogDecoder, encoder=commons.models.LogEncoder)),
            ],
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
