# Generated by Django 5.2.4 on 2025-07-18 05:49

import commons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailedlog',
            options={'verbose_name': 'Detailed Log Entry', 'verbose_name_plural': 'Detailed Log Entries'},
        ),
        migrations.AlterField(
            model_name='detailedlog',
            name='changed_values',
            field=models.JSONField(decoder=commons.models.LogDecoder, encoder=commons.models.LogEncoder, help_text='New values after change'),
        ),
        migrations.AlterField(
            model_name='detailedlog',
            name='old_values',
            field=models.JSONField(decoder=commons.models.LogDecoder, encoder=commons.models.LogEncoder, help_text='Original values before change'),
        ),
    ]
