# Generated by Django 5.2 on 2025-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
            },
        ),
        migrations.AddField(
            model_name="participant",
            name="fixed_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterModelTable(
            name="participant",
            table=None,
        ),
    ]
