# Generated by Django 5.2.1 on 2025-06-04 16:59

import commons.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_course_type'),
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='cost_type',
            field=models.IntegerField(choices=[(1, 'اقامت هتل - ثابت'), (2, 'پذیرایی تیم اجرایی - ثابت'), (3, 'جابجایی تیم اجرایی - ثابت'), (4, 'تجهیزات - ثابت'), (5, 'نیروی خدماتی - ثابت'), (6, 'جبران خدمات تیم اجرا - ثابت'), (7, 'لوازم تحریر - متغیر'), (8, 'پذیرایی - متغیر')]),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('person', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_received', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='courses.course')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
                'ordering': ['-date', '-_created_at'],
            },
            bases=(models.Model,),
        ),
    ]
