# Generated by Django 5.2.1 on 2025-06-04 17:23

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_alter_cost_cost_type_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
