# Generated by Django 5.2.1 on 2025-06-04 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_alter_cost_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='income',
            name='is_received',
        ),
        migrations.RemoveField(
            model_name='income',
            name='person',
        ),
        migrations.RemoveField(
            model_name='income',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='income',
            name='title',
        ),
        migrations.RemoveField(
            model_name='income',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='income',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to=settings.AUTH_USER_MODEL),
        ),
    ]
