# Generated by Django 5.2.4 on 2025-07-10 20:58

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_commodity_customer_invoice_invoiceitem_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-_created_at']},
        ),
        migrations.AlterModelOptions(
            name='financialaccount',
            options={'ordering': ['-_created_at']},
        ),
        migrations.AddField(
            model_name='customer',
            name='_created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='_updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
