# Generated by Django 5.2.4 on 2025-07-11 11:25

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_registration_invoice_item_and_more'),
        ('financials', '0004_alter_customer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='course',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='transaction_type',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.IntegerField(choices=[(1, 'حقیقی'), (2, 'حقوقی')], default=1),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='items_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='orgnization',
            field=models.IntegerField(choices=[(1, 'Neshaa'), (2, 'azno')], default=1),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='entry_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='net_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='vat',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tracking_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='CourseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('_updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('transaction_type', models.IntegerField(choices=[(1, 'دریافت'), (2, 'برداشت')], default=1)),
                ('transaction_category', models.IntegerField(choices=[(1, 'اقامت هتل'), (2, 'پذیرایی تیم اجرایی'), (3, 'جابجایی تیم اجرایی'), (4, 'تجهیزات'), (5, 'نیروی خدماتی'), (6, 'جبران خدمات تیم اجرا'), (7, 'لوازم تحریر'), (8, 'پذیرایی'), (9, 'شارژ اعتبار'), (10, 'ثبت\u200cنام'), (11, 'قسط')], default=1)),
                ('tracking_code', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField(default=0)),
                ('net_amount', models.PositiveIntegerField()),
                ('date', django_jalali.db.models.jDateField()),
                ('customer_name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='courses.course')),
                ('entry_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_transactions_entry', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='courses.registration')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_transactions', to='financials.transaction')),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-_created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
