# Generated by Django 5.2.1 on 2025-06-04 17:49

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_income_is_received_income_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='is_received',
        ),
        migrations.RemoveField(
            model_name='income',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='income',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='cost',
            name='_created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='_updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='_created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='_updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
