# Generated by Django 5.2.4 on 2025-07-11 11:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_remove_income_course_remove_income_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name': 'Commodity', 'verbose_name_plural': 'Commodities'},
        ),
        migrations.AddField(
            model_name='coursetransaction',
            name='financial_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_transactions', to='financials.financialaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
