# Generated by Django 5.2.1 on 2025-06-05 07:12

import commons.models
import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_instructors_course_price_and_more'),
        ('financials', '0006_remove_income_is_received_remove_income_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cost',
            name='total_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('_updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to='courses.course')),
            ],
            options={
                'verbose_name': 'Financial Account',
                'verbose_name_plural': 'Financial Accounts',
                'ordering': ['name'],
            },
            bases=(models.Model,),
        ),
    ]
