# Generated by Django 5.2.4 on 2025-07-11 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_alter_commodity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_category',
            field=models.IntegerField(choices=[(1, 'ثبت\u200cنام دوره'), (2, 'هزینه دوره'), (3, 'قسط دوره'), (4, 'شارژ اعتبار'), (5, 'هزینه عملیاتی'), (6, 'جبران خدمات'), (7, 'تجهیزات'), (8, 'سرمایه\u200cگذاری')], default=1),
        ),
        migrations.AlterField(
            model_name='coursetransaction',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_transactions', to='financials.transaction'),
        ),
    ]
