# Generated by Django 5.2.1 on 2025-06-05 07:38

import commons.models
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_instructors_course_price_and_more'),
        ('financials', '0007_alter_cost_amount_alter_cost_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('_updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_financial_accounts', to='courses.course')),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_accounts', to='financials.financialaccount')),
            ],
            options={
                'verbose_name': 'Course Financial Account',
                'verbose_name_plural': 'Course Financial Accounts',
                'ordering': ['course__id', 'financial_account__id'],
                'unique_together': {('course', 'financial_account')},
            },
            bases=(models.Model,),
        ),
    ]
