# Generated by Django 5.2.4 on 2025-07-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_transaction_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetransaction',
            name='transaction_category',
            field=models.IntegerField(choices=[(1, 'اقامت هتل'), (2, 'پذیرایی تیم اجرایی'), (3, 'جابجایی تیم اجرایی'), (4, 'تجهیزات'), (5, 'نیروی خدماتی'), (6, 'جبران خدمات تیم اجرا'), (7, 'لوازم تحریر'), (8, 'پذیرایی'), (9, 'شارژ اعتبار'), (10, 'ثبت\u200cنام'), (11, 'قسط')], default=10),
        ),
    ]
