# Generated by Django 5.2.4 on 2025-07-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_alter_coursetransaction_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetransaction',
            name='amount',
            field=models.PositiveIntegerField(help_text='تومان'),
        ),
        migrations.AlterField(
            model_name='coursetransaction',
            name='fee',
            field=models.PositiveIntegerField(default=0, help_text='تومان'),
        ),
        migrations.AlterField(
            model_name='coursetransaction',
            name='net_amount',
            field=models.PositiveIntegerField(help_text='تومان'),
        ),
    ]
