# Generated by Django 5.2.1 on 2025-06-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_instructors_course_price_and_more'),
        ('financials', '0008_coursefinancialaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaccount',
            name='course',
        ),
        migrations.DeleteModel(
            name='CourseFinancialAccount',
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='financial_accounts', to='courses.course'),
        ),
    ]
