# Generated by Django 5.2.4 on 2025-07-18 13:26

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0009_alter_coursetransaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetransaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.AddField(
            model_name='coursetransaction',
            name='transaction_date',
            field=django_jalali.db.models.jDateField(db_index=True, default=jdatetime.datetime.now, help_text='تاریخ تراکنش'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=django_jalali.db.models.jDateTimeField(db_index=True, default=jdatetime.datetime.now, help_text='تاریخ تراکنش'),
        ),
    ]
