# Generated by Django 5.2.4 on 2025-07-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0011_alter_coursetransaction_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetransaction',
            name='transaction_category',
            field=models.IntegerField(choices=[(1, 'اقامت هتل'), (2, 'پذیرایی تیم اجرایی'), (3, 'جابجایی تیم اجرایی'), (4, 'تجهیزات'), (5, 'نیروی خدماتی'), (6, 'جبران خدمات تیم اجرا'), (7, 'لوازم تحریر'), (8, 'پذیرایی'), (9, 'شارژ اعتبار'), (10, 'ثبت\u200cنام'), (11, 'قسط'), (12, 'تنخواه')], default=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_category',
            field=models.IntegerField(choices=[(1, 'ثبت\u200cنام دوره'), (2, 'هزینه دوره'), (3, 'قسط دوره'), (4, 'شارژ اعتبار'), (5, 'هزینه عملیاتی'), (6, 'جبران خدمات'), (7, 'تجهیزات'), (8, 'سرمایه\u200cگذاری'), (9, 'تنخواه')], default=1),
        ),
    ]
