# Generated by Django 5.2.4 on 2025-07-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0013_financialaccount_asset_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='orgnization',
            new_name='organization',
        ),
    ]
