# Generated by Django 5.2.4 on 2025-07-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0014_rename_orgnization_invoice_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_category',
            field=models.IntegerField(choices=[(1, 'ثبت\u200cنام دوره'), (2, 'هزینه دوره'), (3, 'قسط دوره'), (4, 'شارژ اعتبار'), (5, 'هزینه عملیاتی'), (6, 'جبران خدمات'), (7, 'تجهیزات'), (8, 'سرمایه\u200cگذاری'), (9, 'تنخواه'), (10, 'قرض و بدهی')], default=1),
        ),
    ]
