# Generated by Django 5.2.4 on 2025-07-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0015_alter_transaction_tracking_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
