# Generated by Django 5.2.4 on 2025-07-29 21:17

import commons.utils
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0016_alter_transaction_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetransaction',
            name='transaction_date',
            field=django_jalali.db.models.jDateTimeField(db_index=True, default=commons.utils.get_jdatetime_now_with_timezone, help_text='تاریخ تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=django_jalali.db.models.jDateTimeField(db_index=True, default=commons.utils.get_jdatetime_now_with_timezone, help_text='تاریخ تراکنش'),
        ),
    ]
