# Generated by Django 5.2 on 2025-06-04 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cost",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Cost",
                "verbose_name_plural": "Costs",
            },
        ),
        migrations.AlterField(
            model_name="cost",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="cost",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterModelTable(
            name="cost",
            table=None,
        ),
    ]
