# Generated by Django 5.2.1 on 2025-07-02 14:45

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('_updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('attended_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-attended_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('_updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.IntegerField(db_index=True)),
                ('price', models.JSONField(blank=True, default=dict)),
                ('start_date', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('end_date', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-_created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('_updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('session_name', models.CharField(max_length=100)),
                ('start_date', django_jalali.db.models.jDateTimeField()),
                ('end_date', django_jalali.db.models.jDateTimeField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Course Session',
                'verbose_name_plural': 'Course Sessions',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('_updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_fa', models.CharField(blank=True, max_length=100, unique=True)),
                ('category', models.IntegerField(choices=[(1, 'دوره'), (2, 'پویش'), (3, 'دیدار'), (4, 'سمینار')], db_index=True, default=1)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-_created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('_updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'در انتظار ثبت\u200cنام'), (2, 'انصراف پیش از دوره'), (3, 'انتخاب نماندن'), (4, 'ترک دوره'), (5, 'حاضر در دوره'), (6, 'اخراج از دوره'), (7, 'تیم اجرایی'), (8, 'مهمان'), (9, 'تکمیل دوره')], default=1)),
                ('registration_date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('tuition', models.IntegerField(default=0, help_text='تومان')),
                ('payment_status', models.IntegerField(choices=[(1, 'عدم سررسید'), (2, 'در انتظار پرداخت'), (3, 'تسویه')], default=3)),
                ('next_payment_date', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'ordering': ['-registration_date'],
            },
        ),
    ]
