# Generated by Django 5.2.1 on 2025-06-04 13:39

import commons.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('course_type', models.CharField(choices=[('دوره\u200cهای پیشوایی', 'دوره\u200cهای پیشوایی'), ('دوره\u200cهای رابطه', 'دوره\u200cهای رابطه'), ('دوره\u200cهای مواجهه', 'دوره\u200cهای مواجهه'), ('تحویل سال دگرگون', 'تحویل سال دگرگون'), ('جان کلام', 'جان کلام'), ('پویش', 'پویش'), ('پیله', 'پیله')], default='دوره\u200cهای پیشوایی', max_length=50)),
                ('course_number', models.CharField(default='1', max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('admin_users', models.ManyToManyField(blank=True, related_name='managed_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-_created_at'],
                'unique_together': {('course_type', 'course_number')},
            },
            bases=(models.Model, commons.models.AuditMixin),
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_updated_at', models.DateTimeField(auto_now=True)),
                ('session_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Session',
                'verbose_name_plural': 'Course Sessions',
                'ordering': ['start_date'],
            },
            bases=(models.Model, commons.models.AuditMixin),
        ),
    ]
