# Generated by Django 5.2.1 on 2025-07-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-_created_at']},
        ),
        migrations.AlterModelOptions(
            name='coursesession',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-registration_date']},
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'نقدی'), (2, 'اقساطی'), (3, 'رایگان'), (4, 'سازمانی')], default=1),
        ),
    ]
