# Generated by Django 5.2.4 on 2025-07-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='تومان'),
        ),
        migrations.AddField(
            model_name='registration',
            name='initial_price',
            field=models.PositiveIntegerField(default=0, help_text='تومان'),
        ),
        migrations.AddField(
            model_name='registration',
            name='vat',
            field=models.PositiveIntegerField(default=0, help_text='تومان'),
        ),
    ]
