# Generated by Django 5.2.1 on 2025-06-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_fee_remove_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_number',
            new_name='number',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_type', 'number')},
        ),
    ]
