# Generated by Django 5.2.4 on 2025-07-11 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_registration_discount_registration_initial_price_and_more'),
        ('financials', '0004_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='invoice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='financials.invoiceitem'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
