# Generated by Django 5.2.4 on 2025-07-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_course_name_alter_course_instructors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='support_user',
            new_name='supporting_user',
        ),
    ]
