# Generated by Django 5.2.4 on 2025-07-18 13:03

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_registration_invoice_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attended_at',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now),
        ),
    ]
