# Generated by Django 5.2.1 on 2025-06-05 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_attendence__created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, help_text='Users who are instructors for this course.', related_name='instructed_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.JSONField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='assisting_users',
            field=models.ManyToManyField(blank=True, related_name='assisted_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='managing_users',
            field=models.ManyToManyField(blank=True, related_name='managed_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
