# Generated by Django 5.2.4 on 2025-08-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_attendance_attended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='joined_group',
            field=models.BooleanField(default=False, help_text='عضویت در گروه دوره'),
        ),
    ]
