# Generated by Django 5.2.4 on 2025-08-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_registration_joined_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0, help_text='تومان'),
        ),
    ]
