# Generated by Django 5.2 on 2025-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="amount_paid",
        ),
        migrations.AddField(
            model_name="registration",
            name="payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name="registration",
            table=None,
        ),
    ]
